# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# Read the Docs configuration file version
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Set Python version and requirements required to build the docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
